# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-28 06:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_marketingpreference_mailchimp_subscribed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingpreference',
            old_name='mailchimp_mas',
            new_name='mailchimp_msg',
        ),
    ]
