# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20171127_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='timestamp',
        ),
    ]
