# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-27 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_remove_usersession_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
